### ISSUE TITLE
Where is 'at-ui-style'

### ISSUE THREAD

**Issue by yoyo837** [AT-UI/at-ui#10]
When i run npm i, it report error like this:
ERROR in ./docs/main.js
Module not found: Error: Can't resolve 'at-ui-style' in 'D:\source-control\git\at-ui\docs'

**Comment by yoyo837** [comment]
Sorry，i found it.

**Comment by yoyo837** [comment]
After run 
```
npm i at-ui-style
```
Same as ever.

**Comment by koppthe** [comment]
I'll improve the documentation.

`at-ui-style` is a submodule of `at-ui`.
You should run two commands: `git submodule init` to initialize your local configuration file, and `git submodule update` to fetch all the data.

```shell
git submodule init
git submodule update
```

**Comment by yoyo837** [comment]
All right. You should do that.

**Comment by yoyo837** [comment]
.gitmodules: Submodule clone with SSH, when at-ui clone with HTTPS, there may be report error.

Host key verification failed.
fatal: Could not read from remote repository.

**Comment by yoyo837** [comment]
#19
