### ISSUE TITLE
Its becoming a pain to create a form

### ISSUE THREAD

**Issue by e200** [AT-UI/at-ui#114]
I'm trying to migrate from bootstrap-vue to at-ui, its an awesome ui kit, but seems like its bringing a lot more work to me instead of agility.

In bootstrap we have a well structured form just adding a <b-form-group> and the inputs inside, but i don't find such helpers at at-tu, another thing I'm facing is that helpers like mx-auto, mb, pb aren't available, there is no style or component for input labels. So, I'm missing something, how do you guys that use this kit make your forms? You need to write your own code to get helpers like those to get a well formed form?

**Comment by joernroeder** [comment]
have you seen https://github.com/AT-UI/at-ui/tree/master/src/components/form/src ?

**Comment by e200** [comment]
@joernroeder, it's not on the official docs.

But its ok now. :)

**Comment by dfmarulanda** [comment]
I cannot use at-form and at-item-form as listed in the components. It doesn't render.
