### ISSUE TITLE
Select 选择器 错误

### ISSUE THREAD

**Issue by intruth** [AT-UI/at-ui#144]
### 希望添加给select组件添加一个data属性
![image](https://user-images.githubusercontent.com/44230075/50104698-b0a3fb80-0265-11e9-8982-d97284900fd1.png)
![image](https://user-images.githubusercontent.com/44230075/50104753-cb767000-0265-11e9-8886-b2c4f93c055f.png)

**Comment by ub3132003** [comment]
你的选项 循环表达能用吗? 当我尝试用 for in 去遍历数组时     value 都是一样的， 但是{{item}} 可以遍历
