### ISSUE TITLE
[at-button] couple of features about at-button

### ISSUE THREAD

**Issue by jason5149** [AT-UI/at-ui#24]
1.add full width property
(I know at-button can be add custom class but I think it should have)

2.disabled property should depend on params to control it 
(I don't find disabled property in document)

**Comment by koppthe** [comment]
1. customize width of `at-button`
```html
<at-button type="primary" style="width:200px;">primary</at-button>
```

2. `disabled` binds with variable
```html
<at-button type="primary" :disabled="disabled">primary</at-button>
```
