### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [AT-UI/at-ui#25]
It will be awesome if a card component could be available.

https://material.io/guidelines/components/cards.html

Cheers

**Comment by koppthe** [comment]
Card component will coming soon in next version. Thx~
#3

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you ;) Is it possible to know when it is going to be available? I really would like to try out this framework but I need a card component

**Comment by koppthe** [comment]
Maybe next week. It will be published in `v.1.3.0`.
Can i know what kinds of card component you prefer to use? Such like [Material Card](https://material.io/guidelines/components/cards.html)

**Comment by FrancescoSaverioZuppichini** [comment]
Yes Material Card would be awesome!
