### ISSUE TITLE
[Request] Need guide using menu with vue-router

### ISSUE THREAD

**Issue by ChangJoo-Park** [AT-UI/at-ui#26]
Hello,

In Breadcrumb docs, It tells how to integrate with vue-router. But **Menu** will use more.
How do I use vue-router with menu component?

**Comment by koppthe** [comment]
I haven't integrated `vue-router` into the menu component yet. I'll add the feature recently. Thanks for your feedback.😃

**Comment by ChangJoo-Park** [comment]
Thank you for reply :) currently I using on-select for router push with parameter(activeName). It works well but It can't change active class

**Comment by xtrimf** [comment]
@ChangJoo-Park  can you show your on-select code - I'm trying to use it and I cannot get it to work.
no example in the docs either....

**Comment by ChangJoo-Park** [comment]
Yes I will :)

**Comment by ChangJoo-Park** [comment]
@xtrimf here you are.
It is repo for explain.
https://github.com/ChangJoo-Park/at-ui-navigation-menu-example

**Add @on-select event**
https://github.com/ChangJoo-Park/at-ui-navigation-menu-example/blob/master/src/App.vue#L3

**Handle Routes**
https://github.com/ChangJoo-Park/at-ui-navigation-menu-example/blob/master/src/App.vue#L16

**Comment by xtrimf** [comment]
tnx @ChangJoo-Park  !
But what if I don't want to use the menu items as links? but rather as "buttons" - each one triggers a different script?
I saw in your example that the `on-select` is  per `at-menu` and I need per `at-menu-item`

any Idea if that's possible?

**Comment by koppthe** [comment]
@ChangJoo-Park @xtrimf

**Comment by koppthe** [comment]
@ChangJoo-Park @xtrimf 
Sorry man, i'm obsessed with my job recently. No time to deal with this issues.
I had integrated vue-router into the menu component. It just hasn't been released yet. 

I'll release it as soon as possible. Thanks :)

**Comment by koppthe** [comment]
#47

**Comment by ChangJoo-Park** [comment]
Thank you @koppthe
