### ISSUE TITLE
Responsive grid must be mobile first

### ISSUE THREAD

**Issue by andrey-hohlov** [AT-UI/at-ui#27]
Hi!

In my case i need 24-col width on xs screen, 18-col width on sm screen and 12-col width on md screen.

```html
<div class="row at-row flex-center">
  <div class="col-xs-24 col-sm-18 col-md-12"></div>
</div>
```

But `sm` always override `xs`:

![token 2017-09-07 10-26-47](https://user-images.githubusercontent.com/7358151/30144731-385aad54-93b7-11e7-87b8-e3e5a5df9b4b.png)

It happens because `max-width` media query used.

**Comment by koppthe** [comment]
Thanks for comment. This will be fixed in the next version today.

**Comment by koppthe** [comment]
#48
