### ISSUE TITLE
.flex-center text-align

### ISSUE THREAD

**Issue by andrey-hohlov** [AT-UI/at-ui#28]
Because `.flex-center` class has `text-align: center` style children elements (like select) break:

![token 2017-09-07 10-35-46](https://user-images.githubusercontent.com/7358151/30144919-5a676e86-93b8-11e7-9716-b3ae95ebb26c.png)

**Comment by andrey-hohlov** [comment]
For example:
```html
<div class="row at-row flex-center">
  <div class="col-sm-24 col-md-12 text-left">
    <at-select v-model="selectedItem" filterable size="large">
      <at-option
        v-for="item in items"
        :key="item.id"
        :label="item.name"
        :value="item.id">
      </at-option>
    </at-select>
  </div>
</div>     
```
(if need I can add this on codepen)

**Comment by koppthe** [comment]
#48
