### ISSUE TITLE
Import On Demand doesn't work

### ISSUE THREAD

**Issue by neves** [AT-UI/at-ui#30]
The docs at https://at-ui.github.io/at-ui/#/en/docs/quickstart says I can import on demand like this:
`import { AtInput } from 'at-ui'` but AtInput is not exported, the correct is Input.

But even if I try to import just Input, it returns undefined:
```javascript
import AtUI, {Input} from 'at-ui'
console.log('AtUI.Input:', AtUI.Input) // ok
console.log('Input:', Input) // undefined
```
# Steps to reproduce

```shell
vue init at-ui/at-template at-ui-bug
cd at-ui-bug
yarn
yarn dev
// add above lines to src/index.js
```

**Comment by Alexis374** [comment]
the same problem.
Perhaps they don't support at all

**Comment by koppthe** [comment]
Sorry, I just came back from vacation today. Very long vacation :( 
I will fixed it recently.

**Comment by koppthe** [comment]
#61
