### ISSUE TITLE
Setting width option on Loading Bar doesn't work and throws Vue warning

### ISSUE THREAD

**Issue by joshstar** [AT-UI/at-ui#35]
Setting the loading bar width via the config doesn't change the height, it remains at 2px.

When calling any of the triggers for the loading bar i.e `this.$Loading.error()` Vue emits the following console warning:
`[Vue warn]: The data property "width" is already declared as a prop. Use prop default value instead.`
This happens regardless if the width was set via .config() or not.

__Steps to reproduce:__
```
this.$Loading.config({
    width: 4,
});

this.$Loading.start();
```

__Versions:__
Vue: 2.4.3,
at-ui: 1.2.0-beta.2

**Comment by goodpixels** [comment]
I'm getting the same error. Please fix!

**Comment by yoyo837** [comment]
Strange that the online site can work fine about this.

https://at-ui.github.io/at-ui/#/en/docs/loadingbar

**Comment by koppthe** [comment]
#48
