### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [AT-UI/at-ui#37]
Is the framework still getting updates? I see future in this but its buggy in some things and misses components, wish i had time to support

**Comment by koppthe** [comment]
Sorry, i am traveling for a month without computer. I will fix the issues and release new components after coming back.

**Comment by diego-lipinski-de-castro** [comment]
Oh okay, hope I can help later on

**Comment by yoyo837** [comment]
@koppthe Hey man, you should start working...

**Comment by koppthe** [comment]
Yep, working~
