### ISSUE TITLE
@click on at-checkbox inside div triggers twice

### ISSUE THREAD

**Issue by therealwolf42** [AT-UI/at-ui#49]
I have the following code:

`<div  @click="addUser(name)"><at-checkbox></at-checkbox></div>`

When I click on that checkbox - the event gets triggered twice. Putting the @click inside the at-checkbox doesn't work.

I've also tried with @select and @change but nothing worked. Ideas?

**Comment by koppthe** [comment]
have you try `@click.native`?

**Comment by therealwolf42** [comment]
@koppthe ah sorry, thought you replied to the other topic. No I actually haven't. Will try that!

**Comment by therealwolf42** [comment]
`@click.native` worked where normal `@click`didn't - thank you!
