### ISSUE TITLE
单个组件引用报错

### ISSUE THREAD

**Issue by aqbjteddy** [AT-UI/at-ui#58]
### Steps to reproduce
1. 按照[quickstart](https://at-ui.github.io/at-ui/#/zh/docs/quickstart) 初始化项目
`vue init at-ui/at-template my-project
`
2. 在main.js中注释掉 全局引用
```js
import Vue from 'vue'
import App from './App.vue'
import 'at-ui-style'
// import AtUI from 'at-ui'

// Vue.use(AtUI)

new Vue({
  el: '#app',
  ...App
})

  ```
3. 在App.vue页面将示例代码拷上去
```js
import { AtInput } from 'at-ui'

export default {
  components: {
    AtInput
  },
  data () {
    return {
      value: 'O2Team'
    }
  }
}
```
```html
<template>
  <div>
    <at-input v-model="value" placeholder="请输入..."></at-input>
  </div>
</template>
```

### Which browser?

chrome 版本 62.0.3202.94（正式版本） （32 位）
### What is expected?
显示input
### What is actually happening?

console报错
vue.esm.js?efeb:574 [Vue warn]: Unknown custom element: <at-input> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by koppthe** [comment]
OK, 今天会修复这个问题，谢谢反馈

**Comment by koppthe** [comment]
#61
