### ISSUE TITLE
How do I use pagination? Is there an example?

### ISSUE THREAD

**Issue by therealwolf42** [AT-UI/at-ui#62]
Your framework is amazing. And I'm trying to use pagination, but I don't see any examples and am not sure how to go forward.

Do you have some code snippets?

**Comment by koppthe** [comment]
such like this?
```html
<at-pagination :total="100" show-total show-sizer show-quickjump @page-change="handlePageChange"></at-pagination>
```
https://at-ui.github.io/at-ui/#/en/docs/pagination

**Comment by therealwolf42** [comment]
Okay got it working now - thank you! :)
