### ISSUE TITLE
咨询一下组件的官网是怎么搭建的

### ISSUE THREAD

**Issue by sirzxj** [AT-UI/at-ui#7]
用了什么开源的系统吗

先把issue close了

**Comment by koppthe** [comment]
官网的源码可以在 `docs` 目录里查看，困难点大概是将 Markdown 文件转换为 vue 的代码，这块可以借助 [vue-markdown-loader](https://github.com/QingWei-Li/vue-markdown-loader) 实现。

**Comment by yoyo837** [comment]
类似hexo那样的方式

**Comment by angelen10** [comment]
@koppthe 如果我想搭建一个类似一本书那样的，如下图：
![](https://ww1.sinaimg.cn/large/006tNc79gy1fj3wi8pox4j31kw0gljuz.jpg)

然后使用组件官网的样式，这个要怎么做呢？

**Comment by yoyo837** [comment]
You should learn HTML, CSS, JS at first.

**Comment by angelen10** [comment]
@yoyo837 我会 HTML, CSS, JS，我是说能不能像 Hexo 那样，我写完 Markdown 文章，部署，然后就可以生成那样的？

**Comment by koppthe** [comment]
@yoyo837 我理解的是，你是想将 AT-UI 的官网做成 Gitbook 的一个主题吗？

**Comment by angelen10** [comment]
@koppthe 对对对，就是这个意思，用 GitBook 或者其他软件编写都行，因为 at-ui 的主题实在太好看了，一见倾心，很想用

**Comment by koppthe** [comment]
@angelen10 嗯嗯，做一套主题也蛮有意思的，这个点不错，赞一个👍
我这边有这个打算，但最近实在太忙了，暂时没法投入，欢迎你创建一个新项目

**Comment by angelen10** [comment]
@koppthe 期待👏

**Comment by koppthe** [comment]
@angelen10 你可以看一下 [Contributing Guidelines](https://github.com/at-ui/at-ui/blob/master/.github/CONTRIBUTING.md)

**Comment by angelen10** [comment]
@koppthe Thanks for that.😉
