### ISSUE TITLE
pull run with wrong

### ISSUE THREAD

**Issue by wued2017** [AT-UI/at-ui#8]
cant resolve ‘at-ui-style’
src/stylesheet file is null

**Comment by koppthe** [comment]
`at-ui-style` is a submodule of `at-ui`.
You should run two commands: `git submodule init` to initialize your local configuration file, and `git submodule update` to fetch all the data.

```shell
git submodule init
git submodule update
```

**Comment by wued2017** [comment]
it worked ,thanks.

**Comment by mage3k** [comment]
It would be better to add this to the part of the contribution

**Comment by koppthe** [comment]
@mage3k thanks for the advice

**Comment by yoyo837** [comment]
Duplicate #10
