### ISSUE TITLE
单组件使用失败，无法引用Notification, Dialog and Message组件

### ISSUE THREAD

**Issue by aqbjteddy** [AT-UI/at-ui#82]
### Steps to reproduce
按照官方示例 https://at-ui.github.io/at-ui/#/zh/docs/quickstart 引用单个组件，以下只有LoadingBar in exports，其它三个没办法以 import 方式从at-ui引用
```js
import {
  Notification,
  Message,
  LoadingBar,
  Dialog
} from 'at-ui'

  Vue.prototype.$Notify = Notification // null
  Vue.prototype.$Loading = LoadingBar
  Vue.prototype.$Modal = Dialog // null
  Vue.prototype.$Message = Message // null
```
我看了下，源代码里没有把那三个加到exports里面

### Which browser?

AT-UI: 1.3.1
### What is expected?
可以引用到Notification、Dialog、Message组件
### What is actually happening?

```js
  Vue.prototype.$Notify = Notification // null
  Vue.prototype.$Loading = LoadingBar
  Vue.prototype.$Modal = Dialog // null
  Vue.prototype.$Message = Message // null
```
### Reproduction Link
不需要

**Comment by koppthe** [comment]
已经有同学提了 PR，只是还没有发版本

**Comment by koppthe** [comment]
#67
