### ISSUE TITLE
Side Navigator collapsible and optimizable Top Navigator for mobile Version

### ISSUE THREAD

**Issue by tobiratzberger** [AT-UI/at-ui#83]
Hello!

Looks like the "Top Navigator" is not optimized for the mobile version.
Did i overlook something or is this a bug?
https://at-ui.github.io/at-ui/#/en/docs/menu

And sorry for asking in a BUG Ticket but, is it possible to collapse and expand the "Side Navigator" - if not, would it be able to include it in one of the next updates?

Greetings, Tobi

**Comment by koppthe** [comment]
sorry, `AT-UI` is incompatible with mobile, so the compatibility of document isn't handled well.
maybe you can submit a pr? : )
