### ISSUE TITLE
Nuxt.js and AT UI (at ui with ssr)

### ISSUE THREAD

**Issue by k1ll1n** [AT-UI/at-ui#94]
For those who want to use AT UI in conjunction with nuxt.js.

You need to create a plugin `~/plugins/at-ui.js`
Further, in `nuxt.config.js`

```
module.exports = {
  plugins: ['~/plugins/at-ui'],
  css: [{src: 'at-ui-style', lang: 'css'}]
}
```

profit!

**Comment by Michael-Reich** [comment]
Any Idea how to use the SCSS?

**Comment by gevera** [comment]
> For those who want to use AT UI in conjunction with nuxt.js.
> 
> You need to create a plugin `~/plugins/at-ui.js`
> Further, in `nuxt.config.js`
> 
> ```
> module.exports = {
>   plugins: ['~/plugins/at-ui'],
>   css: [{src: 'at-ui-style', lang: 'css'}]
> }
> ```
> profit!

Can you provide more details on your at-ui.js

For some reasons, I do get an error. Spasibo

**Comment by ksuzushima** [comment]
@gevera Here is my `at-ui.js` settings

```js
import Vue from 'vue'
import AtUI from 'at-ui'

Vue.use(AtUI)
```

**Comment by gevera** [comment]
> @gevera Here is my `at-ui.js` settings
> 
> ```js
> import Vue from 'vue'
> import AtUI from 'at-ui'
> 
> Vue.use(AtUI)
> ```

Perfect. It worked like a charm. How can we add this to official documentation?

**Comment by ImEins** [comment]
Hey, any idea how to use this library with nuxt 2.15.7 ? I also use yarn instead of npm or maybe I can add it manually without any package manager ?
